/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteRouteImport } from './routes/_dashboardLayout/route'
import { Route as DashboardLayoutOwnerLayoutRouteRouteImport } from './routes/_dashboardLayout/_ownerLayout/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCompleteProfileRouteImport } from './routes/auth/complete-profile'
import { Route as DashboardLayoutOwnerLayoutOwnerIndexRouteImport } from './routes/_dashboardLayout/_ownerLayout/owner/index'
import { Route as DashboardLayoutOwnerLayoutOwnerDashboardIndexRouteImport } from './routes/_dashboardLayout/_ownerLayout/owner/dashboard/index'
import { Route as DashboardLayoutOwnerLayoutOwnerProjectsIndexRouteImport } from './routes/_dashboardLayout/_ownerLayout/owner/projects/index'
import { Route as DashboardLayoutOwnerLayoutOwnerProjectsCreateRouteImport } from './routes/_dashboardLayout/_ownerLayout/owner/projects/create'
import { Route as DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRouteImport } from './routes/_dashboardLayout/_ownerLayout/owner/projects/$projectId/edit'
import { Route as DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRouteImport } from './routes/_dashboardLayout/_ownerLayout/owner/projects/$projectId/proposals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRouteRoute = DashboardLayoutRouteRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutOwnerLayoutRouteRoute =
  DashboardLayoutOwnerLayoutRouteRouteImport.update({
    id: '/_ownerLayout',
    getParentRoute: () => DashboardLayoutRouteRoute,
  } as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/auth/complete-profile',
  path: '/auth/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutOwnerLayoutOwnerIndexRoute =
  DashboardLayoutOwnerLayoutOwnerIndexRouteImport.update({
    id: '/owner/',
    path: '/owner/',
    getParentRoute: () => DashboardLayoutOwnerLayoutRouteRoute,
  } as any)
const DashboardLayoutOwnerLayoutOwnerDashboardIndexRoute =
  DashboardLayoutOwnerLayoutOwnerDashboardIndexRouteImport.update({
    id: '/owner/dashboard/',
    path: '/owner/dashboard/',
    getParentRoute: () => DashboardLayoutOwnerLayoutRouteRoute,
  } as any)
const DashboardLayoutOwnerLayoutOwnerProjectsIndexRoute =
  DashboardLayoutOwnerLayoutOwnerProjectsIndexRouteImport.update({
    id: '/owner/projects/',
    path: '/owner/projects/',
    getParentRoute: () => DashboardLayoutOwnerLayoutRouteRoute,
  } as any)
const DashboardLayoutOwnerLayoutOwnerProjectsCreateRoute =
  DashboardLayoutOwnerLayoutOwnerProjectsCreateRouteImport.update({
    id: '/owner/projects/create',
    path: '/owner/projects/create',
    getParentRoute: () => DashboardLayoutOwnerLayoutRouteRoute,
  } as any)
const DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRoute =
  DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRouteImport.update({
    id: '/owner/projects/$projectId/edit',
    path: '/owner/projects/$projectId/edit',
    getParentRoute: () => DashboardLayoutOwnerLayoutRouteRoute,
  } as any)
const DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRoute =
  DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRouteImport.update({
    id: '/owner/projects/$projectId/proposals',
    path: '/owner/projects/$projectId/proposals',
    getParentRoute: () => DashboardLayoutOwnerLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/owner/': typeof DashboardLayoutOwnerLayoutOwnerIndexRoute
  '/owner/projects/create': typeof DashboardLayoutOwnerLayoutOwnerProjectsCreateRoute
  '/owner/dashboard/': typeof DashboardLayoutOwnerLayoutOwnerDashboardIndexRoute
  '/owner/projects/': typeof DashboardLayoutOwnerLayoutOwnerProjectsIndexRoute
  '/owner/projects/$projectId/edit': typeof DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRoute
  '/owner/projects/$projectId/proposals': typeof DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth': typeof AuthIndexRoute
  '/owner': typeof DashboardLayoutOwnerLayoutOwnerIndexRoute
  '/owner/projects/create': typeof DashboardLayoutOwnerLayoutOwnerProjectsCreateRoute
  '/owner/dashboard': typeof DashboardLayoutOwnerLayoutOwnerDashboardIndexRoute
  '/owner/projects': typeof DashboardLayoutOwnerLayoutOwnerProjectsIndexRoute
  '/owner/projects/$projectId/edit': typeof DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRoute
  '/owner/projects/$projectId/proposals': typeof DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteRouteWithChildren
  '/_dashboardLayout/_ownerLayout': typeof DashboardLayoutOwnerLayoutRouteRouteWithChildren
  '/auth/complete-profile': typeof AuthCompleteProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboardLayout/_ownerLayout/owner/': typeof DashboardLayoutOwnerLayoutOwnerIndexRoute
  '/_dashboardLayout/_ownerLayout/owner/projects/create': typeof DashboardLayoutOwnerLayoutOwnerProjectsCreateRoute
  '/_dashboardLayout/_ownerLayout/owner/dashboard/': typeof DashboardLayoutOwnerLayoutOwnerDashboardIndexRoute
  '/_dashboardLayout/_ownerLayout/owner/projects/': typeof DashboardLayoutOwnerLayoutOwnerProjectsIndexRoute
  '/_dashboardLayout/_ownerLayout/owner/projects/$projectId/edit': typeof DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRoute
  '/_dashboardLayout/_ownerLayout/owner/projects/$projectId/proposals': typeof DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/complete-profile'
    | '/auth/'
    | '/owner/'
    | '/owner/projects/create'
    | '/owner/dashboard/'
    | '/owner/projects/'
    | '/owner/projects/$projectId/edit'
    | '/owner/projects/$projectId/proposals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/complete-profile'
    | '/auth'
    | '/owner'
    | '/owner/projects/create'
    | '/owner/dashboard'
    | '/owner/projects'
    | '/owner/projects/$projectId/edit'
    | '/owner/projects/$projectId/proposals'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/_dashboardLayout/_ownerLayout'
    | '/auth/complete-profile'
    | '/auth/'
    | '/_dashboardLayout/_ownerLayout/owner/'
    | '/_dashboardLayout/_ownerLayout/owner/projects/create'
    | '/_dashboardLayout/_ownerLayout/owner/dashboard/'
    | '/_dashboardLayout/_ownerLayout/owner/projects/'
    | '/_dashboardLayout/_ownerLayout/owner/projects/$projectId/edit'
    | '/_dashboardLayout/_ownerLayout/owner/projects/$projectId/proposals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRouteRoute: typeof DashboardLayoutRouteRouteWithChildren
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/_ownerLayout': {
      id: '/_dashboardLayout/_ownerLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutOwnerLayoutRouteRouteImport
      parentRoute: typeof DashboardLayoutRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete-profile': {
      id: '/auth/complete-profile'
      path: '/auth/complete-profile'
      fullPath: '/auth/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/_ownerLayout/owner/': {
      id: '/_dashboardLayout/_ownerLayout/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof DashboardLayoutOwnerLayoutOwnerIndexRouteImport
      parentRoute: typeof DashboardLayoutOwnerLayoutRouteRoute
    }
    '/_dashboardLayout/_ownerLayout/owner/dashboard/': {
      id: '/_dashboardLayout/_ownerLayout/owner/dashboard/'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard/'
      preLoaderRoute: typeof DashboardLayoutOwnerLayoutOwnerDashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutOwnerLayoutRouteRoute
    }
    '/_dashboardLayout/_ownerLayout/owner/projects/': {
      id: '/_dashboardLayout/_ownerLayout/owner/projects/'
      path: '/owner/projects'
      fullPath: '/owner/projects/'
      preLoaderRoute: typeof DashboardLayoutOwnerLayoutOwnerProjectsIndexRouteImport
      parentRoute: typeof DashboardLayoutOwnerLayoutRouteRoute
    }
    '/_dashboardLayout/_ownerLayout/owner/projects/create': {
      id: '/_dashboardLayout/_ownerLayout/owner/projects/create'
      path: '/owner/projects/create'
      fullPath: '/owner/projects/create'
      preLoaderRoute: typeof DashboardLayoutOwnerLayoutOwnerProjectsCreateRouteImport
      parentRoute: typeof DashboardLayoutOwnerLayoutRouteRoute
    }
    '/_dashboardLayout/_ownerLayout/owner/projects/$projectId/edit': {
      id: '/_dashboardLayout/_ownerLayout/owner/projects/$projectId/edit'
      path: '/owner/projects/$projectId/edit'
      fullPath: '/owner/projects/$projectId/edit'
      preLoaderRoute: typeof DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRouteImport
      parentRoute: typeof DashboardLayoutOwnerLayoutRouteRoute
    }
    '/_dashboardLayout/_ownerLayout/owner/projects/$projectId/proposals': {
      id: '/_dashboardLayout/_ownerLayout/owner/projects/$projectId/proposals'
      path: '/owner/projects/$projectId/proposals'
      fullPath: '/owner/projects/$projectId/proposals'
      preLoaderRoute: typeof DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRouteImport
      parentRoute: typeof DashboardLayoutOwnerLayoutRouteRoute
    }
  }
}

interface DashboardLayoutOwnerLayoutRouteRouteChildren {
  DashboardLayoutOwnerLayoutOwnerIndexRoute: typeof DashboardLayoutOwnerLayoutOwnerIndexRoute
  DashboardLayoutOwnerLayoutOwnerProjectsCreateRoute: typeof DashboardLayoutOwnerLayoutOwnerProjectsCreateRoute
  DashboardLayoutOwnerLayoutOwnerDashboardIndexRoute: typeof DashboardLayoutOwnerLayoutOwnerDashboardIndexRoute
  DashboardLayoutOwnerLayoutOwnerProjectsIndexRoute: typeof DashboardLayoutOwnerLayoutOwnerProjectsIndexRoute
  DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRoute: typeof DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRoute
  DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRoute: typeof DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRoute
}

const DashboardLayoutOwnerLayoutRouteRouteChildren: DashboardLayoutOwnerLayoutRouteRouteChildren =
  {
    DashboardLayoutOwnerLayoutOwnerIndexRoute:
      DashboardLayoutOwnerLayoutOwnerIndexRoute,
    DashboardLayoutOwnerLayoutOwnerProjectsCreateRoute:
      DashboardLayoutOwnerLayoutOwnerProjectsCreateRoute,
    DashboardLayoutOwnerLayoutOwnerDashboardIndexRoute:
      DashboardLayoutOwnerLayoutOwnerDashboardIndexRoute,
    DashboardLayoutOwnerLayoutOwnerProjectsIndexRoute:
      DashboardLayoutOwnerLayoutOwnerProjectsIndexRoute,
    DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRoute:
      DashboardLayoutOwnerLayoutOwnerProjectsProjectIdEditRoute,
    DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRoute:
      DashboardLayoutOwnerLayoutOwnerProjectsProjectIdProposalsRoute,
  }

const DashboardLayoutOwnerLayoutRouteRouteWithChildren =
  DashboardLayoutOwnerLayoutRouteRoute._addFileChildren(
    DashboardLayoutOwnerLayoutRouteRouteChildren,
  )

interface DashboardLayoutRouteRouteChildren {
  DashboardLayoutOwnerLayoutRouteRoute: typeof DashboardLayoutOwnerLayoutRouteRouteWithChildren
}

const DashboardLayoutRouteRouteChildren: DashboardLayoutRouteRouteChildren = {
  DashboardLayoutOwnerLayoutRouteRoute:
    DashboardLayoutOwnerLayoutRouteRouteWithChildren,
}

const DashboardLayoutRouteRouteWithChildren =
  DashboardLayoutRouteRoute._addFileChildren(DashboardLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRouteRoute: DashboardLayoutRouteRouteWithChildren,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
