/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboardLayout'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardLayoutOwnerIndexRouteImport } from './routes/_dashboardLayout/owner/index'
import { Route as DashboardLayoutOwnerDashboardIndexRouteImport } from './routes/_dashboardLayout/owner/dashboard/index'
import { Route as DashboardLayoutOwnerProjectsIndexRouteImport } from './routes/_dashboardLayout/owner/projects/index'
import { Route as DashboardLayoutOwnerProjectsCreateRouteImport } from './routes/_dashboardLayout/owner/projects/create'
import { Route as DashboardLayoutOwnerProjectsProjectIdEditRouteImport } from './routes/_dashboardLayout/owner/projects/$projectId/edit'
import { Route as DashboardLayoutOwnerProjectsProjectIdProposalsRouteImport } from './routes/_dashboardLayout/owner/projects/$projectId/proposals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutOwnerIndexRoute =
  DashboardLayoutOwnerIndexRouteImport.update({
    id: '/owner/',
    path: '/owner/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutOwnerDashboardIndexRoute =
  DashboardLayoutOwnerDashboardIndexRouteImport.update({
    id: '/owner/dashboard/',
    path: '/owner/dashboard/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutOwnerProjectsIndexRoute =
  DashboardLayoutOwnerProjectsIndexRouteImport.update({
    id: '/owner/projects/',
    path: '/owner/projects/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutOwnerProjectsCreateRoute =
  DashboardLayoutOwnerProjectsCreateRouteImport.update({
    id: '/owner/projects/create',
    path: '/owner/projects/create',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutOwnerProjectsProjectIdEditRoute =
  DashboardLayoutOwnerProjectsProjectIdEditRouteImport.update({
    id: '/owner/projects/$projectId/edit',
    path: '/owner/projects/$projectId/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutOwnerProjectsProjectIdProposalsRoute =
  DashboardLayoutOwnerProjectsProjectIdProposalsRouteImport.update({
    id: '/owner/projects/$projectId/proposals',
    path: '/owner/projects/$projectId/proposals',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/owner/': typeof DashboardLayoutOwnerIndexRoute
  '/owner/projects/create': typeof DashboardLayoutOwnerProjectsCreateRoute
  '/owner/dashboard/': typeof DashboardLayoutOwnerDashboardIndexRoute
  '/owner/projects/': typeof DashboardLayoutOwnerProjectsIndexRoute
  '/owner/projects/$projectId/edit': typeof DashboardLayoutOwnerProjectsProjectIdEditRoute
  '/owner/projects/$projectId/proposals': typeof DashboardLayoutOwnerProjectsProjectIdProposalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/auth': typeof AuthIndexRoute
  '/owner': typeof DashboardLayoutOwnerIndexRoute
  '/owner/projects/create': typeof DashboardLayoutOwnerProjectsCreateRoute
  '/owner/dashboard': typeof DashboardLayoutOwnerDashboardIndexRoute
  '/owner/projects': typeof DashboardLayoutOwnerProjectsIndexRoute
  '/owner/projects/$projectId/edit': typeof DashboardLayoutOwnerProjectsProjectIdEditRoute
  '/owner/projects/$projectId/proposals': typeof DashboardLayoutOwnerProjectsProjectIdProposalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboardLayout/owner/': typeof DashboardLayoutOwnerIndexRoute
  '/_dashboardLayout/owner/projects/create': typeof DashboardLayoutOwnerProjectsCreateRoute
  '/_dashboardLayout/owner/dashboard/': typeof DashboardLayoutOwnerDashboardIndexRoute
  '/_dashboardLayout/owner/projects/': typeof DashboardLayoutOwnerProjectsIndexRoute
  '/_dashboardLayout/owner/projects/$projectId/edit': typeof DashboardLayoutOwnerProjectsProjectIdEditRoute
  '/_dashboardLayout/owner/projects/$projectId/proposals': typeof DashboardLayoutOwnerProjectsProjectIdProposalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-profile'
    | '/auth/'
    | '/owner/'
    | '/owner/projects/create'
    | '/owner/dashboard/'
    | '/owner/projects/'
    | '/owner/projects/$projectId/edit'
    | '/owner/projects/$projectId/proposals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/auth'
    | '/owner'
    | '/owner/projects/create'
    | '/owner/dashboard'
    | '/owner/projects'
    | '/owner/projects/$projectId/edit'
    | '/owner/projects/$projectId/proposals'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/complete-profile'
    | '/auth/'
    | '/_dashboardLayout/owner/'
    | '/_dashboardLayout/owner/projects/create'
    | '/_dashboardLayout/owner/dashboard/'
    | '/_dashboardLayout/owner/projects/'
    | '/_dashboardLayout/owner/projects/$projectId/edit'
    | '/_dashboardLayout/owner/projects/$projectId/proposals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/owner/': {
      id: '/_dashboardLayout/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof DashboardLayoutOwnerIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/owner/dashboard/': {
      id: '/_dashboardLayout/owner/dashboard/'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard/'
      preLoaderRoute: typeof DashboardLayoutOwnerDashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/owner/projects/': {
      id: '/_dashboardLayout/owner/projects/'
      path: '/owner/projects'
      fullPath: '/owner/projects/'
      preLoaderRoute: typeof DashboardLayoutOwnerProjectsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/owner/projects/create': {
      id: '/_dashboardLayout/owner/projects/create'
      path: '/owner/projects/create'
      fullPath: '/owner/projects/create'
      preLoaderRoute: typeof DashboardLayoutOwnerProjectsCreateRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/owner/projects/$projectId/edit': {
      id: '/_dashboardLayout/owner/projects/$projectId/edit'
      path: '/owner/projects/$projectId/edit'
      fullPath: '/owner/projects/$projectId/edit'
      preLoaderRoute: typeof DashboardLayoutOwnerProjectsProjectIdEditRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/owner/projects/$projectId/proposals': {
      id: '/_dashboardLayout/owner/projects/$projectId/proposals'
      path: '/owner/projects/$projectId/proposals'
      fullPath: '/owner/projects/$projectId/proposals'
      preLoaderRoute: typeof DashboardLayoutOwnerProjectsProjectIdProposalsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutOwnerIndexRoute: typeof DashboardLayoutOwnerIndexRoute
  DashboardLayoutOwnerProjectsCreateRoute: typeof DashboardLayoutOwnerProjectsCreateRoute
  DashboardLayoutOwnerDashboardIndexRoute: typeof DashboardLayoutOwnerDashboardIndexRoute
  DashboardLayoutOwnerProjectsIndexRoute: typeof DashboardLayoutOwnerProjectsIndexRoute
  DashboardLayoutOwnerProjectsProjectIdEditRoute: typeof DashboardLayoutOwnerProjectsProjectIdEditRoute
  DashboardLayoutOwnerProjectsProjectIdProposalsRoute: typeof DashboardLayoutOwnerProjectsProjectIdProposalsRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutOwnerIndexRoute: DashboardLayoutOwnerIndexRoute,
  DashboardLayoutOwnerProjectsCreateRoute:
    DashboardLayoutOwnerProjectsCreateRoute,
  DashboardLayoutOwnerDashboardIndexRoute:
    DashboardLayoutOwnerDashboardIndexRoute,
  DashboardLayoutOwnerProjectsIndexRoute:
    DashboardLayoutOwnerProjectsIndexRoute,
  DashboardLayoutOwnerProjectsProjectIdEditRoute:
    DashboardLayoutOwnerProjectsProjectIdEditRoute,
  DashboardLayoutOwnerProjectsProjectIdProposalsRoute:
    DashboardLayoutOwnerProjectsProjectIdProposalsRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
