/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboardLayout'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardLayoutOwnerIndexRouteImport } from './routes/_dashboardLayout/owner/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutOwnerIndexRoute =
  DashboardLayoutOwnerIndexRouteImport.update({
    id: '/owner/',
    path: '/owner/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/owner/': typeof DashboardLayoutOwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/auth': typeof AuthIndexRoute
  '/owner': typeof DashboardLayoutOwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboardLayout/owner/': typeof DashboardLayoutOwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/complete-profile' | '/auth/' | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/complete-profile' | '/auth' | '/owner'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/complete-profile'
    | '/auth/'
    | '/_dashboardLayout/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/owner/': {
      id: '/_dashboardLayout/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof DashboardLayoutOwnerIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutOwnerIndexRoute: typeof DashboardLayoutOwnerIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutOwnerIndexRoute: DashboardLayoutOwnerIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
